using Org.Ethasia.Fundetected.Core.Equipment.Affixes;

namespace Org.Ethasia.Fundetected.Ioadapters
{
    public class RollableAffixesPerItemGroupMasterDataProvider
    {
        public AffixRollCalculationTableMasterData CreateRollableSuffixesForOneHandedSwords()
        {
            EquipmentAffix strengthBaseAffix = new PlusStrengthAffix(0);

            var affixRollCalculationTableMasterDataBuilder = new AffixRollCalculationTableMasterData.Builder()
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(9)
                    .SetMinItemLevel(1)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(8)
                        .SetMaxValue(12)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(11)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(13)
                        .SetMaxValue(17)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(22)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(18)
                        .SetMaxValue(22)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(33)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(23)
                        .SetMaxValue(27)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(44)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(28)
                        .SetMaxValue(32)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(55)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(33)
                        .SetMaxValue(37)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(66)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(38)
                        .SetMaxValue(42)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(74)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(43)
                        .SetMaxValue(50)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(82)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(51)
                        .SetMaxValue(55)
                        .SetIncrement(1)
                        .Build())
                    .Build());

            EquipmentAffix agilityBaseAffix = new PlusAgilityAffix(0);

            affixRollCalculationTableMasterDataBuilder
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(9)
                    .SetMinItemLevel(1)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(8)
                        .SetMaxValue(12)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(11)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(13)
                        .SetMaxValue(17)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(22)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(18)
                        .SetMaxValue(22)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(33)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(23)
                        .SetMaxValue(27)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(44)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(28)
                        .SetMaxValue(32)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(55)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(33)
                        .SetMaxValue(37)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(66)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(38)
                        .SetMaxValue(42)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(74)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(43)
                        .SetMaxValue(50)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(82)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(51)
                        .SetMaxValue(55)
                        .SetIncrement(1)
                        .Build())
                    .Build());

            return affixRollCalculationTableMasterDataBuilder.Build();
        }

        public AffixRollCalculationTableMasterData CreateRollablePrefixesForOneHandedSwords()
        {
            EquipmentAffix physicalDamageBaseAffix = new PlusMinMaxPhysicalDamageAffix(0, 0);

            var affixRollCalculationTableMasterDataBuilder = new AffixRollCalculationTableMasterData.Builder()
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(9)
                    .SetMinItemLevel(2)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(1)
                        .SetLowerBoundMaxValue(1)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(2)
                        .SetUpperBoundMaxValue(3)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(13)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(4)
                        .SetLowerBoundMaxValue(5)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(8)
                        .SetUpperBoundMaxValue(9)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(21)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(6)
                        .SetLowerBoundMaxValue(9)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(13)
                        .SetUpperBoundMaxValue(15)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(29)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(8)
                        .SetLowerBoundMaxValue(12)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(17)
                        .SetUpperBoundMaxValue(20)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(36)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(11)
                        .SetLowerBoundMaxValue(14)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(21)
                        .SetUpperBoundMaxValue(25)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(46)
                    .SetWeighting(800)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(13)
                        .SetLowerBoundMaxValue(18)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(27)
                        .SetUpperBoundMaxValue(31)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(54)
                    .SetWeighting(600)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(16)
                        .SetLowerBoundMaxValue(21)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(32)
                        .SetUpperBoundMaxValue(38)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(65)
                    .SetWeighting(400)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(19)
                        .SetLowerBoundMaxValue(25)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(39)
                        .SetUpperBoundMaxValue(45)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(77)
                    .SetWeighting(200)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(22)
                        .SetLowerBoundMaxValue(29)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(45)
                        .SetUpperBoundMaxValue(52)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build());

            return affixRollCalculationTableMasterDataBuilder.Build();            
        }
    }
}