using Org.Ethasia.Fundetected.Core.Equipment.Affixes;

namespace Org.Ethasia.Fundetected.Ioadapters
{
    public class RollableAffixesPerItemGroupMasterDataProvider
    {
        public AffixRollCalculationTableMasterData CreateRollablePrefixesForOneHandedSwords()
        {
            EquipmentAffix physicalDamageBaseAffix = new PlusMinMaxPhysicalDamageAffix(0, 0);

            var affixRollCalculationTableMasterDataBuilder = new AffixRollCalculationTableMasterData.Builder()
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(9)
                    .SetMinItemLevel(2)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(1)
                        .SetLowerBoundMaxValue(1)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(2)
                        .SetUpperBoundMaxValue(3)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(13)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(4)
                        .SetLowerBoundMaxValue(5)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(8)
                        .SetUpperBoundMaxValue(9)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(21)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(6)
                        .SetLowerBoundMaxValue(9)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(13)
                        .SetUpperBoundMaxValue(15)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(29)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(8)
                        .SetLowerBoundMaxValue(12)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(17)
                        .SetUpperBoundMaxValue(20)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(36)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(11)
                        .SetLowerBoundMaxValue(14)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(21)
                        .SetUpperBoundMaxValue(25)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(46)
                    .SetWeighting(800)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(13)
                        .SetLowerBoundMaxValue(18)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(27)
                        .SetUpperBoundMaxValue(31)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(54)
                    .SetWeighting(600)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(16)
                        .SetLowerBoundMaxValue(21)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(32)
                        .SetUpperBoundMaxValue(38)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(65)
                    .SetWeighting(400)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(19)
                        .SetLowerBoundMaxValue(25)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(39)
                        .SetUpperBoundMaxValue(45)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(77)
                    .SetWeighting(200)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(physicalDamageBaseAffix)
                        .SetLowerBoundMinValue(22)
                        .SetLowerBoundMaxValue(29)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(45)
                        .SetUpperBoundMaxValue(52)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build());

            return affixRollCalculationTableMasterDataBuilder.Build();            
        }

        public AffixRollCalculationTableMasterData CreateRollableSuffixesForOneHandedSwords()
        {
            EquipmentAffix strengthBaseAffix = new PlusStrengthAffix(0);

            var affixRollCalculationTableMasterDataBuilder = new AffixRollCalculationTableMasterData.Builder()
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(9)
                    .SetMinItemLevel(1)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(8)
                        .SetMaxValue(12)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(11)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(13)
                        .SetMaxValue(17)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(22)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(18)
                        .SetMaxValue(22)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(33)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(23)
                        .SetMaxValue(27)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(44)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(28)
                        .SetMaxValue(32)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(55)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(33)
                        .SetMaxValue(37)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(66)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(38)
                        .SetMaxValue(42)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(74)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(43)
                        .SetMaxValue(50)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(82)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(51)
                        .SetMaxValue(55)
                        .SetIncrement(1)
                        .Build())
                    .Build());

            EquipmentAffix agilityBaseAffix = new PlusAgilityAffix(0);

            affixRollCalculationTableMasterDataBuilder
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(9)
                    .SetMinItemLevel(1)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(8)
                        .SetMaxValue(12)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(11)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(13)
                        .SetMaxValue(17)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(22)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(18)
                        .SetMaxValue(22)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(33)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(23)
                        .SetMaxValue(27)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(44)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(28)
                        .SetMaxValue(32)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(55)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(33)
                        .SetMaxValue(37)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(66)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(38)
                        .SetMaxValue(42)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(74)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(43)
                        .SetMaxValue(50)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(82)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(51)
                        .SetMaxValue(55)
                        .SetIncrement(1)
                        .Build())
                    .Build());

            EquipmentAffix increasedAttackSpeedBaseAffix = new IncreasedAttackSpeedAffix(0);

            affixRollCalculationTableMasterDataBuilder
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(1)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(increasedAttackSpeedBaseAffix)
                        .SetMinValue(5)
                        .SetMaxValue(7)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(11)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(increasedAttackSpeedBaseAffix)
                        .SetMinValue(8)
                        .SetMaxValue(10)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(22)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(increasedAttackSpeedBaseAffix)
                        .SetMinValue(11)
                        .SetMaxValue(13)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(30)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(increasedAttackSpeedBaseAffix)
                        .SetMinValue(14)
                        .SetMaxValue(16)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(37)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(increasedAttackSpeedBaseAffix)
                        .SetMinValue(17)
                        .SetMaxValue(19)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(45)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(increasedAttackSpeedBaseAffix)
                        .SetMinValue(20)
                        .SetMaxValue(22)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(60)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(increasedAttackSpeedBaseAffix)
                        .SetMinValue(23)
                        .SetMaxValue(25)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(77)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(increasedAttackSpeedBaseAffix)
                        .SetMinValue(26)
                        .SetMaxValue(27)
                        .SetIncrement(1)
                        .Build())
                    .Build());

            return affixRollCalculationTableMasterDataBuilder.Build();
        }

        public AffixRollCalculationTableMasterData CreateRollablePrefixesForRings()
        {
            EquipmentAffix maximumLifeBaseAffix = new PlusMaximumLifeAffix(0);

            var affixRollCalculationTableMasterDataBuilder = new AffixRollCalculationTableMasterData.Builder()
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(1)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumLifeBaseAffix)
                        .SetMinValue(3)
                        .SetMaxValue(9)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(5)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumLifeBaseAffix)
                        .SetMinValue(10)
                        .SetMaxValue(24)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(11)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumLifeBaseAffix)
                        .SetMinValue(25)
                        .SetMaxValue(39)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(18)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumLifeBaseAffix)
                        .SetMinValue(40)
                        .SetMaxValue(54)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(24)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumLifeBaseAffix)
                        .SetMinValue(55)
                        .SetMaxValue(69)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(30)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumLifeBaseAffix)
                        .SetMinValue(70)
                        .SetMaxValue(84)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(36)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumLifeBaseAffix)
                        .SetMinValue(85)
                        .SetMaxValue(99)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(44)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumLifeBaseAffix)
                        .SetMinValue(100)
                        .SetMaxValue(114)
                        .SetIncrement(1)
                        .Build())
                    .Build());

            EquipmentAffix maximumManaBaseAffix = new PlusMaximumManaAffix(0);

            affixRollCalculationTableMasterDataBuilder
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(13)
                    .SetMinItemLevel(1)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(15)
                        .SetMaxValue(19)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(12)
                    .SetMinItemLevel(11)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(20)
                        .SetMaxValue(24)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(11)
                    .SetMinItemLevel(17)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(25)
                        .SetMaxValue(29)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(10)
                    .SetMinItemLevel(23)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(30)
                        .SetMaxValue(34)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(9)
                    .SetMinItemLevel(29)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(35)
                        .SetMaxValue(39)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(35)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(40)
                        .SetMaxValue(44)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(42)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(45)
                        .SetMaxValue(49)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(51)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(50)
                        .SetMaxValue(54)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(60)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(55)
                        .SetMaxValue(59)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(69)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(60)
                        .SetMaxValue(64)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(75)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(65)
                        .SetMaxValue(68)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(81)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(69)
                        .SetMaxValue(73)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(85)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(maximumManaBaseAffix)
                        .SetMinValue(74)
                        .SetMaxValue(78)
                        .SetIncrement(1)
                        .Build())
                    .Build());

            EquipmentAffix globalPhysicalDamageWithAttacksBaseAffix = new PlusMinMaxGlobalPhysicalDamageWithAttacksAffix(0, 0);

            affixRollCalculationTableMasterDataBuilder
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(5)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(globalPhysicalDamageWithAttacksBaseAffix)
                        .SetLowerBoundMinValue(1)
                        .SetLowerBoundMaxValue(1)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(2)
                        .SetUpperBoundMaxValue(2)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(13)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(globalPhysicalDamageWithAttacksBaseAffix)
                        .SetLowerBoundMinValue(2)
                        .SetLowerBoundMaxValue(3)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(4)
                        .SetUpperBoundMaxValue(5)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(19)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(globalPhysicalDamageWithAttacksBaseAffix)
                        .SetLowerBoundMinValue(3)
                        .SetLowerBoundMaxValue(4)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(6)
                        .SetUpperBoundMaxValue(7)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(28)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(globalPhysicalDamageWithAttacksBaseAffix)
                        .SetLowerBoundMinValue(4)
                        .SetLowerBoundMaxValue(6)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(9)
                        .SetUpperBoundMaxValue(10)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(35)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(globalPhysicalDamageWithAttacksBaseAffix)
                        .SetLowerBoundMinValue(5)
                        .SetLowerBoundMaxValue(7)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(11)
                        .SetUpperBoundMaxValue(12)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(44)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerIntervalMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(globalPhysicalDamageWithAttacksBaseAffix)
                        .SetLowerBoundMinValue(6)
                        .SetLowerBoundMaxValue(9)
                        .SetLowerBoundIncrement(1)
                        .SetUpperBoundMinValue(13)
                        .SetUpperBoundMaxValue(15)
                        .SetUpperBoundIncrement(1)
                        .Build())
                    .Build());

            return affixRollCalculationTableMasterDataBuilder.Build();            
        }

        public AffixRollCalculationTableMasterData CreateRollableSuffixesForRings()
        {
            EquipmentAffix strengthBaseAffix = new PlusStrengthAffix(0);

            var affixRollCalculationTableMasterDataBuilder = new AffixRollCalculationTableMasterData.Builder()
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(9)
                    .SetMinItemLevel(1)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(8)
                        .SetMaxValue(12)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(11)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(13)
                        .SetMaxValue(17)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(22)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(18)
                        .SetMaxValue(22)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(33)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(23)
                        .SetMaxValue(27)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(44)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(28)
                        .SetMaxValue(32)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(55)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(33)
                        .SetMaxValue(37)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(66)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(38)
                        .SetMaxValue(42)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(74)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(43)
                        .SetMaxValue(50)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(82)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(strengthBaseAffix)
                        .SetMinValue(51)
                        .SetMaxValue(55)
                        .SetIncrement(1)
                        .Build())
                    .Build());

            EquipmentAffix agilityBaseAffix = new PlusAgilityAffix(0);

            affixRollCalculationTableMasterDataBuilder
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(9)
                    .SetMinItemLevel(1)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(8)
                        .SetMaxValue(12)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(11)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(13)
                        .SetMaxValue(17)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(22)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(18)
                        .SetMaxValue(22)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(33)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(23)
                        .SetMaxValue(27)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(44)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(28)
                        .SetMaxValue(32)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(55)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(33)
                        .SetMaxValue(37)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(66)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(38)
                        .SetMaxValue(42)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(74)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(43)
                        .SetMaxValue(50)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(82)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(agilityBaseAffix)
                        .SetMinValue(51)
                        .SetMaxValue(55)
                        .SetIncrement(1)
                        .Build())
                    .Build());

            EquipmentAffix intelligenceBaseAffix = new PlusIntelligenceAffix(0);

            affixRollCalculationTableMasterDataBuilder
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(9)
                    .SetMinItemLevel(1)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(intelligenceBaseAffix)
                        .SetMinValue(8)
                        .SetMaxValue(12)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(8)
                    .SetMinItemLevel(11)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(intelligenceBaseAffix)
                        .SetMinValue(13)
                        .SetMaxValue(17)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(7)
                    .SetMinItemLevel(22)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(intelligenceBaseAffix)
                        .SetMinValue(18)
                        .SetMaxValue(22)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(6)
                    .SetMinItemLevel(33)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(intelligenceBaseAffix)
                        .SetMinValue(23)
                        .SetMaxValue(27)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(5)
                    .SetMinItemLevel(44)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(intelligenceBaseAffix)
                        .SetMinValue(28)
                        .SetMaxValue(32)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(4)
                    .SetMinItemLevel(55)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(intelligenceBaseAffix)
                        .SetMinValue(33)
                        .SetMaxValue(37)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(3)
                    .SetMinItemLevel(66)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(intelligenceBaseAffix)
                        .SetMinValue(38)
                        .SetMaxValue(42)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(2)
                    .SetMinItemLevel(74)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(intelligenceBaseAffix)
                        .SetMinValue(43)
                        .SetMaxValue(50)
                        .SetIncrement(1)
                        .Build())
                    .Build())
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(82)
                    .SetWeighting(1000)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(intelligenceBaseAffix)
                        .SetMinValue(51)
                        .SetMaxValue(55)
                        .SetIncrement(1)
                        .Build())
                    .Build());

            EquipmentAffix increasedGlobalAttackSpeedBaseAffix = new IncreasedGlobalAttackSpeedAffix(0);

            affixRollCalculationTableMasterDataBuilder
                .AddRollableAffix(new AffixRollCalculationTableEntryMasterData.Builder()
                    .SetTier(1)
                    .SetMinItemLevel(1)
                    .SetWeighting(500)
                    .SetRollableAffix(new IntegerMinMaxIncrementRollableEquipmentAffix.Builder()
                        .SetRerolledAffix(increasedGlobalAttackSpeedBaseAffix)
                        .SetMinValue(5)
                        .SetMaxValue(7)
                        .SetIncrement(1)
                        .Build())
                    .Build());

            return affixRollCalculationTableMasterDataBuilder.Build();          
        }
    }
}